# Auth REST Client
@base_url = localhost:8081
###
GET http://{{base_url}}/api/v1/auth/google?redirect_uri=http://localhost:3000/oauth/callback
###
GET http://{{base_url}}/api/v1/auth/google/callback?code=TEST_CODE&state=TEST_STATE