GET http://localhost:3000/api/courses
Accept: application/json
###
GET http://localhost:3000/api/courses/course-1
Accept: application/json

HTTP/1.1 200  - OK
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
date: Sat, 04 Oct 2025 08:59:08 GMT
connection: close
transfer-encoding: chunked